PID   | Time                    | Level       | Function             |                    File:No | Message
------+-------------------------+-------------+----------------------+----------------------------+-----------------------------------------
34270 | 2025-05-14 13:30:19,375 | 🔵 info     | log_wrap             |                   logab:0  | Program starts...
34270 | 2025-05-14 13:30:20,379 | 🔵 info     | <module>             |                 main.py:20 | 0
34270 | 2025-05-14 13:30:21,379 | 🔵 info     | <module>             |                 main.py:20 | 1
34270 | 2025-05-14 13:30:21,379 | 🟡 warning  | print_main           |                 main.py:13 | In log main
34270 | 2025-05-14 13:30:22,380 | 🔵 info     | <module>             |                 main.py:20 | 2
34270 | 2025-05-14 13:30:22,380 | 🟢 debug    | supermegaprint       |           tests/temp.py:13 | nam kha
34270 | 2025-05-14 13:30:22,381 | 🟡 warning  | <module>             |                 main.py:25 | Loss: 2 游客
34270 | 2025-05-14 13:30:22,381 | 🟣 critical | <module>             |                 main.py:26 | Loss: 2 au cuộc đàm phán cuối tuần trước, Mỹ và Trung Quốc thống nhất tạm hoãn một phần thuế đối ứng trong 90 ngày, đồng thời giảm đáng kể tổng thuế nhập khẩu.
34270 | 2025-05-14 13:30:23,381 | 🔵 info     | <module>             |                 main.py:20 | 3
34270 | 2025-05-14 13:30:24,381 | 🔵 info     | <module>             |                 main.py:20 | 4
34270 | 2025-05-14 13:30:25,382 | 🔵 info     | <module>             |                 main.py:20 | 5
34270 | 2025-05-14 13:30:25,382 | 🟢 debug    | a_very_long_function |           tests/temp.py:17 | nam kha
34270 | 2025-05-14 13:30:26,383 | 🔵 info     | <module>             |                 main.py:20 | 6
34270 | 2025-05-14 13:30:26,383 | 🟢 debug    | newfunc              | tests/utils/newutils.py:6  | Im the best
34270 | 2025-05-14 13:30:27,384 | 🔵 info     | <module>             |                 main.py:20 | 7
34270 | 2025-05-14 13:30:27,385 | 🔴 error    | log_wrap             |                   logab:0  | [Errno 2] No such file or directory: 'abc.txt'
------+-------------------------+-------------+----------------------+----------------------------+-----------------------------------------
Traceback (most recent call last):
  File "/home/namkha/Documents/mydev/logab/logab/log_utils.py", line 151, in log_wrap
    yield
  File "/home/namkha/Documents/mydev/logab/main.py", line 32, in <module>
    cause_error()
  File "/home/namkha/Documents/mydev/logab/tests/temp.py", line 20, in cause_error
    error2_func()
  File "/home/namkha/Documents/mydev/logab/tests/utils/error2.py", line 5, in error2_func
    error1_func()
  File "/home/namkha/Documents/mydev/logab/tests/utils/error1.py", line 2, in error1_func
    with open('abc.txt', 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'abc.txt'
------+-------------------------+-------------+----------------------+----------------------------+-----------------------------------------
34270 | 2025-05-14 13:30:27,385 | 🔵 info     | log_wrap             |                   logab:0  | Execution time 8.0100 seconds
