from tests.utils.error1 import error1_func


def error2_func():
    error1_func()